name: deploy

on:
  push:
    branches:
      - v*
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"

      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 562b9363d491e3ee281cb46944445fcd
          gist_description: Checks if a Scene/Performer is present in Stash
          file_path: dist/index.prod.user.js
          file_type: text
